{
 "title": "PerServer",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "server", "label": "Server IP", "query": "192.168.42.23" },
   {
    "name": "power_base",
    "query": "query_result(min_over_time(ipmi_dcmi_power_consumption_watts{instance=~\"$server:.+\"}[1y]))"
   },
   {
    "name": "cpu_nodes",
    "query": "query_result(count(node_cpu_frequency_hertz{instance=~\"$server:.+\"}))"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<h2 style=\"text-align:center;\">Detailed Overview for Server:<br> <b>$server</b></h2>"
  },
  {
   "title": "Power Consumption Per User",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "(label_replace(ipmi_dcmi_power_consumption_watts{instance=~\"$server:.+\"}, \"ip\", \"$1\", \"instance\", \"(.*):.+\") - $power_base)\n  * \n  on(ip) \n  group_right() \n(\n  clamp_max( \n    ( \n      sum( \n        label_replace(cpup{instance=~\"$server:.+\"}, \"ip\", \"$1\", \"instance\", \"(.*):.+\")\n      ) by (user, ip)\n      / $cpu_nodes\n    ), 100\n  ) \n  / 100\n)",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Consumption above IDLE",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "ipmi_dcmi_power_consumption_watts{instance=~\"$server:.+\"} - $power_base",
     "legendFormat": "Consumption above IDLE"
    }
   ]
  },
  {
   "title": "CPU per User",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "clamp_max(sum (cpup{instance=~\"$server:.+\"}) by (user) / scalar(count(node_cpu_frequency_hertz{instance=~\"$server:.+\"})), 100)",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "CPU per Process (> 5%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cpup{instance=~\"$server:.+\"} > 3",
     "legendFormat": "{{command}} ({{user}})"
    }
   ]
  },
  {
   "title": "Memory per User",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (memp{instance=~\"$server:.+\"}) by (user)",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Memory per Process (> 5%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "memp{instance=~\"$server:.+\"} > 5",
     "legendFormat": "{{command}} ({{user}})"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server:.*\"} / scalar(count(node_cpu_frequency_hertz{instance=~\"$server:.*\"})) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}