{
 "title": "PowerGraphs",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "server", "label": "List of all Servers", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Power Heatmap",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ipmi_dcmi_power_consumption_watts",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Server IP",
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 6 },
   "repeat": "server",
   "content": "<h2 style=\"text-align:center;\">$server</h2>"
  },
  {
   "title": "Server IP",
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 6 },
   "content": "<h2 style=\"text-align:center;\">$server</h2>"
  },
  {
   "title": "Server IP",
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 6 },
   "content": "<h2 style=\"text-align:center;\">$server</h2>"
  },
  {
   "title": "Power Consumption (IPMI)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "repeat": "server",
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "ipmi_dcmi_power_consumption_watts{instance=~\"$server:.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Power Consumption (IPMI)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "ipmi_dcmi_power_consumption_watts{instance=~\"$server:.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Power Consumption (IPMI)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "ipmi_dcmi_power_consumption_watts{instance=~\"$server:.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "repeat": "server",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server:.*\"} / scalar(count(node_cpu_frequency_hertz{instance=~\"$server:.*\"})) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server:.*\"} / scalar(count(node_cpu_frequency_hertz{instance=~\"$server:.*\"})) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server:.*\"} / scalar(count(node_cpu_frequency_hertz{instance=~\"$server:.*\"})) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average CPU Clock Frequency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
   "repeat": "server",
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "avg(node_cpu_frequency_hertz{instance=~\"$server:.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average CPU Clock Frequency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "avg(node_cpu_frequency_hertz{instance=~\"$server:.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average CPU Clock Frequency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "avg(node_cpu_frequency_hertz{instance=~\"$server:.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 35 },
   "repeat": "server",
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "min(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Min Temp"
    },
    {
     "expr": "avg(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Avg Temp"
    },
    {
     "expr": "max(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Max Temp"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "min(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Min Temp"
    },
    {
     "expr": "avg(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Avg Temp"
    },
    {
     "expr": "max(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Max Temp"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "min(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Min Temp"
    },
    {
     "expr": "avg(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Avg Temp"
    },
    {
     "expr": "max(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Max Temp"
    }
   ]
  }
 ]
}