{
 "title": "PowerGraphs",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "server", "label": "List of all Servers", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Power Heatmap",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ipmi_dcmi_power_consumption_watts",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Server IP",
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 6 },
   "repeat": "server",
   "content": "<h2 style=\"text-align:center;\">$server</h2>"
  },
  {
   "title": "Server IP",
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 6 },
   "content": "<h2 style=\"text-align:center;\">$server</h2>"
  },
  {
   "title": "Server IP",
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 6 },
   "content": "<h2 style=\"text-align:center;\">$server</h2>"
  },
  {
   "title": "Server IP",
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 6 },
   "content": "<h2 style=\"text-align:center;\">$server</h2>"
  },
  {
   "title": "Server IP",
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 8 },
   "content": "<h2 style=\"text-align:center;\">$server</h2>"
  },
  {
   "title": "Server IP",
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 8 },
   "content": "<h2 style=\"text-align:center;\">$server</h2>"
  },
  {
   "title": "Server IP",
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 8 },
   "content": "<h2 style=\"text-align:center;\">$server</h2>"
  },
  {
   "title": "Server IP",
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 8 },
   "content": "<h2 style=\"text-align:center;\">$server</h2>"
  },
  {
   "title": "Server IP",
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 10 },
   "content": "<h2 style=\"text-align:center;\">$server</h2>"
  },
  {
   "title": "Server IP",
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 10 },
   "content": "<h2 style=\"text-align:center;\">$server</h2>"
  },
  {
   "title": "Power Consumption (IPMI)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 12 },
   "repeat": "server",
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "ipmi_dcmi_power_consumption_watts{instance=~\"$server:.+\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Power Consumption (IPMI)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "ipmi_dcmi_power_consumption_watts{instance=~\"$server:.+\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Power Consumption (IPMI)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "ipmi_dcmi_power_consumption_watts{instance=~\"$server:.+\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Power Consumption (IPMI)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "ipmi_dcmi_power_consumption_watts{instance=~\"$server:.+\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Power Consumption (IPMI)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "ipmi_dcmi_power_consumption_watts{instance=~\"$server:.+\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Power Consumption (IPMI)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "ipmi_dcmi_power_consumption_watts{instance=~\"$server:.+\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Power Consumption (IPMI)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "ipmi_dcmi_power_consumption_watts{instance=~\"$server:.+\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Power Consumption (IPMI)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "ipmi_dcmi_power_consumption_watts{instance=~\"$server:.+\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Power Consumption (IPMI)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "ipmi_dcmi_power_consumption_watts{instance=~\"$server:.+\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Power Consumption (IPMI)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "ipmi_dcmi_power_consumption_watts{instance=~\"$server:.+\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 102 },
   "repeat": "server",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server:.+\"} / scalar(count(node_cpu_frequency_hertz{instance=~\"$server:.+\"})) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server:.+\"} / scalar(count(node_cpu_frequency_hertz{instance=~\"$server:.+\"})) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server:.+\"} / scalar(count(node_cpu_frequency_hertz{instance=~\"$server:.+\"})) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server:.+\"} / scalar(count(node_cpu_frequency_hertz{instance=~\"$server:.+\"})) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 138 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server:.+\"} / scalar(count(node_cpu_frequency_hertz{instance=~\"$server:.+\"})) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 147 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server:.+\"} / scalar(count(node_cpu_frequency_hertz{instance=~\"$server:.+\"})) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 156 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server:.+\"} / scalar(count(node_cpu_frequency_hertz{instance=~\"$server:.+\"})) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 165 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server:.+\"} / scalar(count(node_cpu_frequency_hertz{instance=~\"$server:.+\"})) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 174 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server:.+\"} / scalar(count(node_cpu_frequency_hertz{instance=~\"$server:.+\"})) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 183 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server:.+\"} / scalar(count(node_cpu_frequency_hertz{instance=~\"$server:.+\"})) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average CPU Clock Frequency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 192 },
   "repeat": "server",
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "avg(node_cpu_frequency_hertz{instance=~\"$server:.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average CPU Clock Frequency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 201 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "avg(node_cpu_frequency_hertz{instance=~\"$server:.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average CPU Clock Frequency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 210 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "avg(node_cpu_frequency_hertz{instance=~\"$server:.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average CPU Clock Frequency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 219 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "avg(node_cpu_frequency_hertz{instance=~\"$server:.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average CPU Clock Frequency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 228 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "avg(node_cpu_frequency_hertz{instance=~\"$server:.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average CPU Clock Frequency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 237 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "avg(node_cpu_frequency_hertz{instance=~\"$server:.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average CPU Clock Frequency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 246 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "avg(node_cpu_frequency_hertz{instance=~\"$server:.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average CPU Clock Frequency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 255 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "avg(node_cpu_frequency_hertz{instance=~\"$server:.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average CPU Clock Frequency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 264 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "avg(node_cpu_frequency_hertz{instance=~\"$server:.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average CPU Clock Frequency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 273 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "avg(node_cpu_frequency_hertz{instance=~\"$server:.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 282 },
   "repeat": "server",
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "min(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Min Temp"
    },
    {
     "expr": "avg(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Avg Temp"
    },
    {
     "expr": "max(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Max Temp"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 291 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "min(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Min Temp"
    },
    {
     "expr": "avg(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Avg Temp"
    },
    {
     "expr": "max(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Max Temp"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 300 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "min(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Min Temp"
    },
    {
     "expr": "avg(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Avg Temp"
    },
    {
     "expr": "max(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Max Temp"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 309 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "min(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Min Temp"
    },
    {
     "expr": "avg(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Avg Temp"
    },
    {
     "expr": "max(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Max Temp"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 318 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "min(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Min Temp"
    },
    {
     "expr": "avg(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Avg Temp"
    },
    {
     "expr": "max(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Max Temp"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 327 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "min(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Min Temp"
    },
    {
     "expr": "avg(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Avg Temp"
    },
    {
     "expr": "max(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Max Temp"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 336 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "min(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Min Temp"
    },
    {
     "expr": "avg(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Avg Temp"
    },
    {
     "expr": "max(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Max Temp"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 345 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "min(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Min Temp"
    },
    {
     "expr": "avg(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Avg Temp"
    },
    {
     "expr": "max(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Max Temp"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 354 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "min(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Min Temp"
    },
    {
     "expr": "avg(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Avg Temp"
    },
    {
     "expr": "max(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Max Temp"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 363 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "min(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Min Temp"
    },
    {
     "expr": "avg(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Avg Temp"
    },
    {
     "expr": "max(node_hwmon_temp_celsius{chip=~'platform_coretemp.*',instance=~\"$server:.*\"})",
     "legendFormat": "Max Temp"
    }
   ]
  }
 ]
}